apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartagri-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartagri
  template:
    metadata:
      labels:
        app: smartagri
    spec:
      containers:
      - name: smartagri-backend
        image: smartagri/backend:latest
        ports:
        - containerPort: 8000
